### ISSUE TITLE
Show player answers when done

### ISSUE THREAD

**Issue by majate** [Gustavrohss/EverythingIsWrong#29] opened 2020-04-15 15:20 UTC
Players should not be possible to see the correct answer before everyone has answered.

**Comment by Gustavrohss** [comment] 2020-04-22 20:01
This is more complicated than it first appears.

In its' current state, this is the structure:
GameRoundComponent has a showResults argument.
GameRoundContainer maps state to showResults through getShowAnswers(state) (a selector).
getShowAnswers gets this info from state.gameSession.showAnswers (a part of the Redux tree).
The only place in gameSessionReducer where showAnswers is set to anything but false is in the SET_SHOW_ANSWERS on switch(action.type).
This is called by the answerQuestion action simply as dispatch(setShowAnswers(true)).

Preferably, this dispatch would be conditional.
const show = Object.keys(state.gameSession.players)
    .map(player => state.gameSession.players[player].status)
    .every(status => status = STATUS.ready))
dispatch(setShowAnswers(show))


However, even when last to answer, the if statement boolean will evaluate to false and the dispatch will not happen. It has something to do with the update in the redux state being delayed. 

I've tried a few workarounds. This includes messing around in the modifyPlayer action (and it's corresponding redux reducer state/switch) and setShowAnswers.

It seems the issue is very intertwined with how backend.js works, and I'm not very familiar. 

What we'd like to happen is - whenever a player answers a question (or possibly just whenever a player state is updated) we would like to check if all players are STATUS.ready (defined in gameSessionActions as "READY") (this can be done with the above code snippet) and dispatch the result. I'm not entirely sure what callbacks are triggered by updates caused by the backend.js listeners. I'm assigning this to Maja and Daniel as you're more familiar with the architecture of this. Hopefully this comment speeds up the process.

**Comment by majate** [comment] 2020-04-22 20:37
My guess is that it should be quite easy to update. Instead of using the "showAnswer" state that is set to true whenever the player answers a question, we can make the getShowAnswer selector check if all players have answered or not.

**Comment by majate** [comment] 2020-04-22 20:39
Made a quick test in another branch and it worked 😃 Can clean the code up and merge it with master later

**Comment by Gustavrohss** [comment] 2020-04-22 20:51
Nice! You could just push it and leave the cleanup for another day. Guessing it's mostly removing the old "show" part of the redux tree, and it's late. :)

**Closed** 2020-04-23 19:53 UTC
Labels: in progress
